
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  servlet:
    multipart:
      max-file-size: 10MB
---
spring:
  profiles:
    default: production
hoaxify:
  upload-path: storage-production
---
spring:
  profiles:
    active: dev
hoaxify:
  upload-path: storage-dev
