spring:
  datasource:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
#spring:
#  datasource:
#    url: jdbc:h2:.devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update
